### ISSUE TITLE
Release process

### ISSUE THREAD

**Issue by julioz** [nodejs/corepack#105]
Seeing that the last release was in Oct 2021 (7 months ago), what are the expectations for the corepack release process?

* Which conditions must be satisfied for a new version cut to be expected?
* Who performs a new release?
* Is the release process manual or can it be automated?
* Should we set up a nightly build release process through npm for "cutting-edge" consumers?

**Comment by merceyz** [comment]
> Is the release process manual or can it be automated?

Manual, but we want to automate it, see https://github.com/nodejs/corepack/issues/90

**Comment by julioz** [comment]
@merceyz What are the open issues/milestones before a new release (even if manually prepared) is cut and made available? Pragmatically speaking, we would like to see some of the changes that landed months ago on `main` be released.

**Comment by arcanis** [comment]
Once https://github.com/nodejs/corepack/pull/106 has landed I'll need to update the CI to auto-publish upgrades (by which point you'll be able to run `npm i -g corepack`), then after that I'll open a PR to Node and it'll ship with the next Node release.

**Comment by merceyz** [comment]
> then after that I'll open a PR to Node and it'll ship with the next Node release.

@arcanis the bot should update it on its own.

**Comment by aduh95** [comment]
> * Is the release process manual or can it be automated?

Since you opened this issue, it has been automated. 

> * Who performs a new release?

We're using [Release Please](https://github.com/google-github-actions/release-please-action) to create automated release PRs, and to create npm releases + git tags + GitHub releases when the PR is merged.

> * Which conditions must be satisfied for a new version cut to be expected?

Anyone asking for it I think, and someone in @nodejs/corepack merging the release PR.


> * Should we set up a nightly build release process through npm for "cutting-edge" consumers?

What would be to set up on our side to make this happen?



> Pragmatically speaking, we would like to see some of the changes that landed months ago on `main` be released.

I agree it would be great to see more momentum around Corepack development, if anyone reading this thread would like to volunteer to join @nodejs/corepack to help review PRs and issue triaging, that would be much welcome.

**Comment by aduh95** [comment]
No follow up closing. Regarding nightlies, we can discuss that if the need comes back in the future, but tbh I think it's simply easier if we simply release more often (which is much easier now that we have an automated process for it).
