### ISSUE TITLE
Corepack use yarn@latest doesn't work

### ISSUE THREAD

**Issue by rotu** [nodejs/corepack#328]
Trying to install `yarn@latest` doesn't work and provides little guidance:

```
corepack use yarn@latest
Usage Error: Tag not found (latest)

$ corepack use <pattern>
```

Note that, for npm and pnpm, the available tags correspond to the published package name on npm and can be seen with:

- `npm info npm dist-tags versions`
- `npm info pnpm dist-tags versions` 

For yarn, `npm info yarn@latest` and `npm info 'yarn@*'` resolve to `yarn@1.22.19`, which is confusing

The available versions for yarn seem to be the union of `npm info yarn versions` and `npm info @yarnpkg/cli versions`. The dist-tags are (maybe) `stable` and `canary`.

---

On invalid input, this command should probably print some hint on what tags are valid or how to enumerate the valid tags (rather than the opaque "`<pattern>`" or "`tag`").

**Comment by aduh95** [comment]
Yarn doesn't use npm for its releases:

https://github.com/nodejs/corepack/blob/0bd2577bb4c6c3a5a33ecdb3b6ca2ff244c54f28/config.json#L131-L145

So it shouldn't be surprising that using npm yields different results. And Yarn registry does not have a `latest` tag, which is why the documentation suggests using `corepack use 'yarn@*'`, which works everywhere (albeit needing to escape the `*` or to use quotes to workaround the shell trying to expand the command is annoying). Whether Yarn registry should have a `latest` tag is up to the Yarn team, not something that Corepack controls.

> On invalid input, this command should probably print some hint on what tags are valid or how to enumerate the valid tags (rather than the opaque "`<pattern>`" or "`tag`").

That sounds great, at least we could hint that using `*` should work when the user tries an invalid tag name. Do you want to send a PR?

**Comment by rotu** [comment]
The yarn package *does* have a `latest` tag, that is on version 1.22.21: https://yarnpkg.com/package?q=yarn&name=yarn&version=1.22.21

Also, the `@yarnpkg/cli` package (where it looks like it's pulling `yarn.js`) has a `latest` tag.

I don't know what https://repo.yarnpkg.com/tags is - it seems like a yarn-specific implementation detail that does not belong in corepack.

Having this yarn-specific special case is odd, especially since the syntax `yarn@xxx` is the exact same syntax as a package specifier recognized by yarn itself (`yarn install yarn@latest`). I'd recommend leaning on the yarn team to bring the project back under a single, canonical versioned package (even if the "default" version is frozen to the 1.x series)

**Comment by rotu** [comment]
> I agree that having a `latest` tag would be good for consistency with other package managers, I'll look into that at some point.

I *don't* think it's a good idea to add another `latest` tag which disagrees with the `dist-tags` listed in `npm info yarn@latest` - it's confusingly ambiguous.
