### ISSUE TITLE
Why corepack bundled with nodejs?

### ISSUE THREAD

**Issue by Cufoon** [nodejs/corepack#576]
In fact, I hate corepack very much. This package has no role in my development. If I want to upgrade corepack, using `npm i -g corepack` will cause problems with my pnpm and yarn. It's disgusting. If I want to use npm, yes, it is already included in node. If I want to use pnpm, I can just `npm i -g pnpm`, and the same is true for yarn. Under what circumstances would I leave this extremely convenient method unused and use `corepack pnpm`. Am I crazy? OK, even if corepack is useful, is it necessary to bundle it with nodejs? Absolutely not. It's ridiculous that you still use `npm i -g corepack` in your readme, and recommend using the version bundled with nodejs. I really think you are telling a joke and bringing pain to all node users.

**Comment by aduh95** [comment]
I think you have the option of not installing Corepack alongside Node.js. If you're building your own `node` binaries, you'd need to pass `--without-corepack` to `./configure` script. If you're using an official Node.js installer, there should be a checkbox you can untick. If you're getting `node` from somewhere else, you'd need to ask whoever is maintaining it what are the options. There's also always the option of ignoring the `corepack` binaries, as long as you don't interact with it, it won't interact with you :)
I hope I answered your question, closing as I don't think there's much that can be done from Corepack's side.

**Comment by Cufoon** [comment]
I downloaded the prebuilt binaries from `nodejs.org`, which is supplied by a compressed file to install nodejs. So is it safe to run `npm rm -g corepack`? Will uninstalling corepack affect any functionality of nodejs?

**Comment by aduh95** [comment]
`corepack` requires `node`, not the other way around, just as `npm`, it's certainly fine to use Node.js standalone.

**Comment by Cufoon** [comment]
OK, I see. Thank you!

**Comment by styfle** [comment]
> Under what circumstances would I leave this extremely convenient method 

Give this blog post a read: https://styfle.dev/blog/corepack

> even if corepack is useful, is it necessary to bundle it with nodejs? 

Its not strictly necessary but it is extremely useful.

Many developers use Node.js with some package manager (npm/yarn/pnpm/etc). And the question comes, how do I install that package manager? How do other devs contributing to the same project install that same version of the package manager? Take pnpm for instance - there are [15 ways to install pnpm](https://pnpm.io/installation) which is very overwhelming for a newbie and prone to error. And several months later when you try to upgrade pnpm, you'll forget which way it was installed and try a different way which won't work due to the precedence of PATH.

`corepack enable pnpm` is nice because it "just works" - handles the package manager, the version, the path, and you don't need to figure out how to install corepack even.
