### ISSUE TITLE
Recommended mechanism for packaging corepack

### ISSUE THREAD

**Issue by ambasta** [nodejs/corepack#76]
Given that corepack is disabled by default, how does one package it for a distribution. Specifically, corepack enable creates symlinks to /usr/bin directly.

This is problematic since 
- It requires superuser access
- It overrides the file managed by distro package manager

Is it safe to create symlinks directly to pnp[mx].js and yarn[pkg].js ? Or is this subject to change over time?

**Comment by arcanis** [comment]
> Is it safe to create symlinks directly to pnp[mx].js and yarn[pkg].js ? Or is this subject to change over time?

Which files do you have in mind?

Generally, my goal for Yarn is to make it installed by Corepack exclusively, not by distributions (with Corepack itself being installed along with Node). Locking package manager versions is as important as locking any other dependencies, and system package managers aren't a good fit for this model.

**Comment by arcanis** [comment]
One gotcha which I think isn't well explained by my previous message: while Yarn versions aren't meant to be installed by distributions (because it'd preclude you from using different ones on a per project basis), the Corepack _shims_ are static (they don't rely on the exact package manager version), so they could be installed by the distribution at the same time as Node (basically, it'd be the same as auto-enabling Corepack).

So, say, the `nodejs` debian package could potentially contain:

```
/usr/bin/node
/usr/bin/yarn -> /usr/lib/node_modules/corepack/shims/yarn
/usr/lib/node_modules/corepack/shims/yarn
```

(Has [`cmdtest`](https://packages.debian.org/sid/cmdtest) been [removed](https://packages.debian.org/sid/all/cmdtest/filelist) from sid?)

**Comment by ambasta** [comment]
@arcanis Thanks for the explanation. I was indeed speaking for the shims that otherwise get symlinked when invoking "corepack enable"

As to a followup, is the list of shims expected to change over time? If so, is it feasible to invoke corepack enable as part of the build process?

Currenltly, when packaging corepack, I am installing the shims manually. Alternately, invoking corepack enable $INSTALLDIR could be a workaround if the list of shims or their install paths are subject to change, though this would be less ideal than doing this in the build/install step provided by nodejs.

For your reference, [this](https://github.com/ambasta/ambasta/commit/c7aa13b3ff433a7a1ba34dffd285cab44a014a4a) is how I'm currently packaging corepack

**Comment by arcanis** [comment]
> As to a followup, is the list of shims expected to change over time? If so, is it feasible to invoke corepack enable as part of the build process?

Since a specific Node version always ships with a same Corepack version, the shims are static for a given Node distribution (if we add any, it won't be expected to be distributed with previous Node releases).
